name: 'Move Linear issues and add labels'
description: 'Action that allows to move issues to a workflow status and add a specified label.'
icon: 'arrow-right-circle'
color: 'purple'
inputs:
  linear_token:
    description: 'Access token for Linear API'
    required: true
  from_status_name:
    description: 'Status name (case insensitive) from which issues will be moved'
    required: true
  to_status_name:
    description: 'New status name (case insensitive) to move issues to'
    required: true
  label_name:
    description: 'Name of the label to add'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.linear_token }}
    - ${{ inputs.from_status_name }}
    - ${{ inputs.to_status_name }}
    - ${{ inputs.label_name }}